### ISSUE TITLE
Support primitive types

### ISSUE THREAD

**Issue by TeofilC** [glguy/th-abstraction#113]
Primitive types like `Int#, (->)` are currently not supported by th-abstraction and lead to an error if you try to reify them.

I'd like to add support for these by handling [PrimTyConI](https://hackage.haskell.org/package/template-haskell-2.20.0.0/docs/Language-Haskell-TH-Syntax.html#v:PrimTyConI) constructor we get from `reify`.

If this sounds alright, I'd be happy to implement this

**Comment by RyanGlScott** [comment]
I'm not necessarily opposed to this idea, but what is the intended use case? I ask since primitive types have no notion of data constructors, so `th-abstraction` wouldn't be able to tell you anything about a primitive type's `ConstructorInfo`s. I suppose `th-abstraction` could tell you about the kind of a primitive type, but then again, you could just as well accomplish this by using `reifyType`. Perhaps I'm missing something, however.

**Comment by TeofilC** [comment]
Good point. 
My use case is that I have a library that tells you whether a type is deep strict and if not, what parts are lazy.
I have some custom TH code to do this right now, but I'd like to transition to using `th-abstraction`.

To calculate whether `Int` is deepstrict we'd recurse into the constructor (`I# Int#`) and see if `Int#` is itself deep strict.
But right now I couldn't do this using `th-abstraction` as it would give me an error.

I could work around this by first doing one reify to check if it's primitive and then calling the th-abstraction functions if it's not. Or by hardcoding whether primitive types are deep-strict. But I think it's nicer to support this case natively in `th-abstraction`.

**Comment by RyanGlScott** [comment]
Ah, I see. Consistency is a nice property to have, so I can see the appeal in having `th-abstraction` return _something_ for primitive types.

I think the only remaining question is: what precisely should the `DatatypeInfo` be for a primitive type? Most of the fields would be straightforward to fill out by inspecting the kind via `reifyType`, similarly to how `th-abstraction` does things currently. The only thing that isn't quite as obvious is what to put for the `datatypeVariant`. I can see two possible options:

1 Create a new `Primitive` constructor of `DatatypeVariant` specifically for primitive data types. We could consider putting the fields of `PrimTyConI` in this variant, such as the `Arity` and `Unlifted` fields.
2. Simply use `Datatype` as the `DatatypeVariant`.

The advantage of option (1) is that it is a bit more precise, and you would be able to know exactly which things correspond to `PrimTyConI`s. The downside is that it requires adding a new constructor to `DatatypeVariant`, which is a breaking API change. (Then again, the next release of `th-abstraction` will need to include breaking changes anyway, so perhaps this isn't that big of a deal.) It's also unclear to me whether the `Arity` and `Unlifted` fields of `PrimTyConI` are even that important, since you can infer this information from other parts of the `DatatypeInfo`.

Option (2) is less precise, but then again, Template Haskell itself is somewhat imprecise about what constitutes a `PrimTyConI` and what doesn't (for instance, unboxed tuples aren't `PrimTyConI`s). In light of this, it doesn't seem that controversial to simply use the `Datatype` variant for all primitive types.

**Comment by TeofilC** [comment]
I originally thought (1) but on reflection I think (2) is best, since, as you point out, things like unboxed tuples aren't represented by `PrimTyConI`. So it doesn't feel like "primitive" types correspond to a well-defined concept.

I think as well a lot of this code smells of having to special case this stuff from when GHC didn't have proper support for unboxed/unlifted things.

I wonder as well if this constructor could be deprecated by TH. I don't see why TH can't just return a `TyConI` for these builtin types like it does for others. I'll make a GHC issue about this soon

**Comment by RyanGlScott** [comment]
> I wonder as well if this constructor [`PrimTyConI`] could be deprecated by TH. I don't see why TH can't just return a TyConI for these builtin types like it does for others.

The only thing that comes to mind is that without `PrimTyConI`, it would not be straightforward to tell if something like `Int#` is a primitive type or an ordinary unlifted data type with zero constructors. For `th-abstraction` purposes, however, I don't think this makes that much of a difference. That is: I'm also on board with picking option (2).
