### ISSUE TITLE
Implicit kind equalities due to GADTs + PolyKinds are not captured

### ISSUE THREAD

**Issue by glguy** [glguy/th-abstraction#6]
The translation of

```
data T :: k -> * where T :: T Int
```

Does not account for implicit `k ~ *` on the constructor

**Comment by RyanGlScott** [comment]
To be honest, I think this is OK. After all, the things we're equating are really the _variable_ of kind `k` and `Int`—the fact that `k ~ *` just happens to fall out as a consequence.

But there is one unsavory thing about the way `th-abstraction` handles this sort of GADT currently—it reports something which isn't kind correct! That is, `reifyDatatype ''T` will currently give you:

```haskell
DatatypeInfo
  { datatypeContext = []
  , datatypeName = T
  , datatypeVars =
      [ SigT (VarT a_6989586621679013870) (VarT k_6989586621679013861) ]
  , datatypeVariant = Datatype
  , datatypeCons =
      [ ConstructorInfo
          { constructorName = T
          , constructorVars = []
          , constructorContext =
              [ AppT
                  (AppT EqualityT (VarT a_6989586621679013870)) (ConT GHC.Types.Int)
              ]
          , constructorFields = []
          , constructorVariant = NormalConstructor
          }
      ]
  }
```

According to the `constructorContext`, `a ~ Int`. But that's not really true, since if you tried writing that back:

```haskell
data T (a :: k) = (a ~ Int) => T
```

You'll get a kind error:

```
    • Expected kind ‘k’, but ‘Int’ has kind ‘*’
    • In the definition of data constructor ‘T’
      In the data declaration for ‘T’
```

The "proper" way to write this would be:

```haskell
import Data.Type.Equality

data T (a :: k) = (a ~~ Int) => T
```

Using the heterogeneous equality type `(~~)` (available in GHC 8.0 and later). But trying to figure out when to use `ConT (~~)` and when to use `EqualityT` is, I think, just as difficult as the original problem, since that would require performing kind inference in Template Haskell...

**Comment by RyanGlScott** [comment]
On second thought, we don't need to be able to distinguish between `ConT (~~)` and `EqualityT`, since `a ~~ b` always implies `a ~ b`. You can say that `a ~ b` has strictly more information than `a ~~ b`, but I don't consider it to be the job of `th-abstraction` to do the kind inference to figure this out.

Therefore, I think a simple fix to this problem would be to just insert `ConT (~~)` instead of `EqualityT` in `normalizeGadtC`. This can only be done in GHC 8.0 or later, but then again, that coincides with the earliest GHC in which you could introduce kind equalities anyway.

Does that sound agreeable?

**Comment by RyanGlScott** [comment]
We ended up deciding against the approach proposed in https://github.com/glguy/th-abstraction/issues/6#issuecomment-304543409. See https://github.com/glguy/th-abstraction/pull/23#issuecomment-307514815 for a rationale.

I think the most satisfactory solution here would be making a note of this behavior in the documentation.
