### ISSUE TITLE
Fails to build against GHC HEAD

### ISSUE THREAD

**Issue by andrewthad** [glguy/th-abstraction#82]
I'm getting this error:

```
src/Language/Haskell/TH/Datatype.hs:217:31: error:
    • Expecting one more argument to ‘TyVarBndr’
      Expected a type, but ‘TyVarBndr’ has kind ‘* -> *’
    • In the type ‘[TyVarBndr]’
      In the definition of data constructor ‘ConstructorInfo’
      In the data declaration for ‘ConstructorInfo’
    |
217 |   , constructorVars       :: [TyVarBndr]        -- ^ Constructor type parameters
    |                               ^^^^^^^^^
```

**Comment by RyanGlScott** [comment]
See #81. Since there hasn't been a release candidate of GHC 8.12 yet, I'm going to wait before submitting a PR to address that, since the `template-haskell` API could still conceivably change between now and then. Until then, I'd recommend using [`head.hackage`](https://gitlab.haskell.org/ghc/head.hackage), which has a suitable `th-abstraction` patch.

**Comment by RyanGlScott** [comment]
I've uploaded [`th-abstraction-0.4.0.0`](http://hackage.haskell.org/package/th-abstraction-0.4.0.0) to Hackage with support for GHC 9.0 (which is what you called HEAD at the time of posting).
