### ISSUE TITLE
data family arity difference

### ISSUE THREAD

**Issue by Lysxia** [glguy/th-abstraction#95]
Are the following data families equivalent?

```
data family F :: Type -> Type
data family F (a :: Type) :: Type
```

Both let me define

```
data instance F [a] = C
```

But the issue is that `reifyDatatype` gives different `dataypeInstTypes`. This leads `kind-generics` to produce a garbage instance for `F :: Type -> Type` (`GenericK F` instead of the expected `GenericK (F [a])`).

```
-- data family F :: Type -> Type
DatatypeInfo {
  datatypeInstTypes = [],
  ... }

-- data family F (a :: Type) :: Type
DatatypeInfo {
  datatypeInstTypes = [AppT ListT (VarT a)],
  ... }
```

**Comment by RyanGlScott** [comment]
Just so that I can distinguish the two sorts of data families (and have a standalone test program), let's call the `:: Type -> Type` variant `F1` and the `(a :: Type) :: Type` variant `F2`:

```hs
{-# LANGUAGE PackageImports #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
module Main where

import                  Data.Kind (Type)
import                  Language.Haskell.TH (reify, stringE)
import "th-abstraction" Language.Haskell.TH.Datatype (reifyDatatype)
import "pretty-show"    Text.Show.Pretty (ppShow)

data family F1 :: Type -> Type
data instance F1 [a] = C1

data family F2 (a :: Type) :: Type
data instance F2 [a] = C2

$(pure [])

main :: IO ()
main = do
  putStrLn $(reifyDatatype 'C1 >>= stringE . ppShow)
  putStrLn $(reifyDatatype 'C2 >>= stringE . ppShow)

```

This outputs:

```hs
DatatypeInfo
  { datatypeContext = []
  , datatypeName = Main.F1
  , datatypeVars = [ KindedTV a_6989586621679024546 () StarT ]
  , datatypeInstTypes = []
  , datatypeVariant = DataInstance
  , datatypeCons =
      [ ConstructorInfo
          { constructorName = Main.C1
          , constructorVars = []
          , constructorContext = []
          , constructorFields = []
          , constructorStrictness = []
          , constructorVariant = NormalConstructor
          }
      ]
  }
DatatypeInfo
  { datatypeContext = []
  , datatypeName = Main.F2
  , datatypeVars = [ KindedTV a_6989586621679024545 () StarT ]
  , datatypeInstTypes = [ AppT ListT (VarT a_6989586621679024545) ]
  , datatypeVariant = DataInstance
  , datatypeCons =
      [ ConstructorInfo
          { constructorName = Main.C2
          , constructorVars = []
          , constructorContext = []
          , constructorFields = []
          , constructorStrictness = []
          , constructorVariant = NormalConstructor
          }
      ]
  }
```

I agree that it doesn't make sense for the `F1` data instance to have an empty `datatypeInstTypes`, and it would make more sense for it to have ` AppT ListT (VarT a)` instead, like the `F2` data instance has. This would mean that the output of `reifyDatatype` would be functionally identical for `F1` and `F2`'s data instance (aside from the names), but I think that's fine. The only difference between `F1` and `F2` is how the data families are defined, and if you really care about that information, then you should just `reify` `F1` or `F2` directly instead of reifying their data family instances.

**Comment by RyanGlScott** [comment]
As for why the output is different in the first place, this is because `reifyDatatype`'s output is ultimately derived from the output of `reify`. Compare the `reify` output for `F1` versus `F2`:

```hs
FamilyI
  (DataFamilyD Main.F1 [] (Just (AppT (AppT ArrowT StarT) StarT)))
  [ DataInstD
      []
      (Just [ KindedTV a_6989586621679026274 () StarT ])
      (AppT (ConT Main.F1) (AppT ListT (VarT a_6989586621679026274)))
      Nothing
      [ NormalC Main.C1 [] ]
      []
  ]
FamilyI
  (DataFamilyD
     Main.F2 [ KindedTV a_6989586621679026272 () StarT ] (Just StarT))
  [ DataInstD
      []
      (Just [ KindedTV a_6989586621679026273 () StarT ])
      (AppT (ConT Main.F2) (AppT ListT (VarT a_6989586621679026273)))
      Nothing
      [ NormalC Main.C2 [] ]
      []
  ]
```

Note `F1 []` versus `F2 [KindedTV a () StarT]`, the former of which misleads `th-abstraction` into thinking that the `datatypeInstTypes` are empty. To do this correctly, we'll need to "eta expand" `F1`'s definition by taking the return kind `Type -> Type` into account.

**Comment by RyanGlScott** [comment]
I've uploaded [`th-abstraction-0.4.5.0`](https://hackage.haskell.org/package/th-abstraction-0.4.5.0) to Hackage with a fix.
